apiVersion: v1
kind: Pod
metadata:
  name: simple-sink
  labels:
    app: simple-sink
spec:
  containers:
  - name: sink
    image: pxsalehi/simple-sink:0.0.1
    ports:
    - name: web
      containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: simple-sink
spec:
  selector:
    app: simple-sink
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
